#version: '3.1'

services:

  wordpress-db:
    image: mysql:5.7
    container_name: wordpress-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234567890
    volumes:
      - wordpress-db-data:/var/lib/mysql

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 1234567890
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress-db

volumes:
  wordpress-db-data:
  wordpress-data:
 
